title: Distributional Fairness-aware Recommendation
description: Welcome to download DistFair.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

github:
  zip_url: https://drive.google.com/file/d/1Uh72K-T7oU4--wlaDRneeUIKnKHhvBtA/view?usp=sharing
